# permissions for end users to edit myjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myjob-editor-role
rules:
- apiGroups:
  - myjob.github.com
  resources:
  - myjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myjob.github.com
  resources:
  - myjobs/status
  verbs:
  - get
