# permissions for end users to view myjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myjob-viewer-role
rules:
- apiGroups:
  - myjob.github.com
  resources:
  - myjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myjob.github.com
  resources:
  - myjobs/status
  verbs:
  - get
